# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rob Kemp
tagline:          'In Progress'
description:      'Some of the stuff I do'
url:              http://robkemp.github.io
baseurl:          /

author:
  name:           'Rob Kemp'
  url:            https://twitter.com/_robkemp

paginate:         5

# Custom vars
version:          0.1.0

github:           https://github.com/robkemp

cv:               https://github.com/robkemp/robkemp.github.io/blob/master/Kemp_Vitae.pdf
